import pickle

VOCABULARY = pickle.load(open("rcv1_vocab.pkl", "rb"))
VOCAB_SIZE = 10000
SEQ_LEN = 1000

CLASSES = ["C11", "C12", "C13", "C14", "C16", "C17", "C18", "C21", "C22", "C23", "C24", "C31", "C32", "C33",
           "C34", "C41", "C42", "E11", "E12", "E13", "E14", "E21", "E31", "E41", "E51", "E61", "E71",
           "G15", "GCRIM", "GDEF", "GDIP", "GDIS", "GENT", "GENV", "GFAS", "GHEA", "GJOB", "GODD", "GPOL",
           "GPRO", "GREL", "GSCI", "GSPO", "GTOUR", "GVIO", "GVOTE", "GWEA", "GWELF", "M11", "M12", "M13",
           "M14"]

CLASS_NAMES = {"C11": "STRATEGY/PLANS",
               "C12": "LEGAL/JUDICIAL",
               "C13": "REGULATION/POLICY",
               "C14": "SHARE LISTINGS",
               "C16": "INSOLVENCY/LIQUIDITY",
               "C17": "FUNDING/CAPITAL",
               "C18": "OWNERSHIP CHANGES",
               "C21": "PRODUCTION/SERVICES",
               "C22": "NEW PRODUCTS/SERVICES",
               "C23": "RESEARCH/DEVELOPMENT",
               "C24": "CAPACITY/FACILITIES",
               "C31": "MARKETS/MARKETING",
               "C32": "ADVERTISING/PROMOTION",
               "C33": "CONTRACTS/ORDERS",
               "C34": "MONOPOLIES/COMPETITION",
               "C41": "MANAGEMENT",
               "C42": "LABOUR",
               "E11": "ECONOMIC PERFORMANCE",
               "E12": "MONETARY/ECONOMIC",
               "E13": "INFLATION/PRICES",
               "E14": "CONSUMER FINANCE",
               "E21": "GOVERNMENT FINANCE",
               "E31": "OUTPUT/CAPACITY",
               "E41": "EMPLOYMENT/LABOUR",
               "E51": "TRADE/RESERVES",
               "E61": "HOUSING STARTS",
               "E71": "LEADING INDICATORS",
               "G15": "EUROPEAN COMMUNITY",
               "GCRIM": "CRIME, LAW ENFORCEMENT",
               "GDEF": "DEFENCE",
               "GDIP": "INTERNATIONAL RELATIONS",
               "GDIS": "DISASTERS AND ACCIDENTS",
               "GENT": "ARTS, CULTURE, ENTERTAINMENT",
               "GENV": "ENVIRONMENT AND NATURAL WORLD",
               "GFAS": "FASHION",
               "GHEA": "HEALTH",
               "GJOB": "LABOUR ISSUES",
               "GODD": "HUMAN INTEREST",
               "GPOL": "DOMESTIC POLITICS",
               "GPRO": "BIOGRAPHIES, PERSONALITIES, PEOPLE",
               "GREL": "RELIGION",
               "GSCI": "SCIENCE AND TECHNOLOGY",
               "GSPO": "SPORTS",
               "GTOUR": "TRAVEL AND TOURISM",
               "GVIO": "WAR, CIVIL WAR",
               "GVOTE": "ELECTIONS",
               "GWEA": "WEATHER",
               "GWELF": "WELFARE, SOCIAL SERVICES",
               "M11": "EQUITY MARKETS",
               "M12": "BOND MARKETS",
               "M13": "MONEY MARKETS",
               "M14": "COMMODITY MARKETS"}
